name: onPush

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          
      - name: Bulid with Maven
        run: mvn --batch-mode --update-snapshots verify

      #- name: Generate javadoc
      #  run: mvn javadoc:javadoc

      #- name: Upload Javadoc
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: javadoc
      #    path: target/site/apidocs
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deploy javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: '11'
          target-folder: target/site/apidocs
          javadoc-branch: javadoc
          project: maven
