name: onPush

permissions:
  contents: write
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          
      - name: Bulid with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Generate javadoc
        run: mvn javadoc:javadoc

      - name: Upload Javadoc
      #  uses: dev-vince/actions-publish-javadoc@v1.0.1
      #  with:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs

